Name:           ros-jade-rotors-gazebo-plugins
Version:        3.0.0
Release:        0%{?dist}
Summary:        ROS rotors_gazebo_plugins package

Group:          Development/Libraries
License:        ASL 2.0
URL:            https://github.com/ethz-asl/rotors_simulator
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo-devel
Requires:       ros-jade-cv-bridge
Requires:       ros-jade-gazebo-ros
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-mav-msgs
Requires:       ros-jade-octomap
Requires:       ros-jade-octomap-msgs
Requires:       ros-jade-octomap-ros
Requires:       ros-jade-rosbag
Requires:       ros-jade-roscpp
Requires:       ros-jade-rotors-comm
Requires:       ros-jade-rotors-control
Requires:       ros-jade-std-srvs
Requires:       ros-jade-tf
Requires:       yaml-cpp-devel
BuildRequires:  gazebo-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-cv-bridge
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-mav-msgs
BuildRequires:  ros-jade-octomap
BuildRequires:  ros-jade-octomap-msgs
BuildRequires:  ros-jade-octomap-ros
BuildRequires:  ros-jade-rosbag
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rotors-comm
BuildRequires:  ros-jade-rotors-control
BuildRequires:  ros-jade-std-srvs
BuildRequires:  ros-jade-tf
BuildRequires:  yaml-cpp-devel

%description
The rotors_gazebo_plugins package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Apr 28 2017 Fadri Furrer <fadri.furrer@mavt.ethz.ch> - 3.0.0-0
- Autogenerated by Bloom

