Name:           ros-melodic-rotors-gazebo
Version:        2.2.3
Release:        0%{?dist}
Summary:        ROS rotors_gazebo package

Group:          Development/Libraries
License:        ASL 2.0
URL:            https://github.com/ethz-asl/rotors_simulator
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-msgs
Requires:       ros-melodic-gazebo-plugins
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-joy
Requires:       ros-melodic-mav-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rotors-gazebo-plugins
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-gazebo-msgs
BuildRequires:  ros-melodic-gazebo-plugins
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-joy
BuildRequires:  ros-melodic-mav-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rotors-gazebo-plugins
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-xacro

%description
The rotors_gazebo package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Dec 14 2018 Fadri Furrer <fadri.furrer@mavt.ethz.ch> - 2.2.3-0
- Autogenerated by Bloom

* Wed Dec 12 2018 Fadri Furrer <fadri.furrer@mavt.ethz.ch> - 2.2.2-0
- Autogenerated by Bloom

